# Generated by Django 3.0.5 on 2020-11-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=200)),
                ('topics', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('teacherid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.Teacher')),
            ],
        ),
    ]
